require 'dayum.plugins.telescope'
require 'dayum.plugins.go-nvim'
require 'dayum.plugins.indent-blankline'
require 'dayum.plugins.distant'
require 'dayum.plugins.colorizer'
require 'dayum.plugins.gitsigns'
require 'dayum.plugins.formatter'
require 'dayum.plugins.neorg'
require 'dayum.plugins.toggleterm'
require 'dayum.plugins.ts-context'

-- vim.notify = require 'notify'
